server:
  port: 2023
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upload_data_db
    username: root
    password: Krithik@2020
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
